// Copyright (c) 2026 The Bitcoin PoCX developers
// Distributed under the MIT software license; see COPYING.
// Deterministic native functional snapshot: cached199blocks, then100blocks at
// 600second intervals with34MiniWallet self-transfers. Independently reconstructed
// from raw blocks and all18717snapshot bytes; see native-assumeutxo-vectors.json.
                .height = 299,
                .hash_serialized = AssumeutxoHash{uint256{"d3f0f3f9c93f045aa6f34767a7b994bfd6d82dca5009a32698f39907572593d3"}},
                .m_chain_tx_count = 334,
                .blockhash = uint256{"c2cd43d6651342138477e4e1b7239f657aeae309884099051e2f7d7922c6fb17"},
