# Copyright (c) 2026 The Bitcoin PoCX developers
# Distributed under the MIT software license; see COPYING.
# Applicable original unit cases, reviewed replacements and native additions.
# Exact case membership and exclusions: test/pocx/unit-parity.json.
set(POCX_TEST_SOURCES
  ${PROJECT_SOURCE_DIR}/src/test/main.cpp
  ${PROJECT_SOURCE_DIR}/src/test/addrman_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/allocator_tests.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/adapted/amount_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/argsman_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/arith_uint256_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/banman_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/base32_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/base58_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/base64_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/bech32_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/bip32_tests.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/adapted/bip324_tests.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/adapted/blockchain_tests.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/adapted/blockencodings_tests.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/adapted/blockfilter_index_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/blockfilter_tests.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/adapted/blockmanager_tests.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/adapted/bloom_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/bswap_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/caches_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/chain_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/chainstate_write_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/checkqueue_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/cluster_linearize_tests.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/adapted/coins_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/coinscachepair_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/coinstatsindex_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/coinsviewoverlay_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/common_url_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/compress_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/crypto_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/cuckoocache_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/dbwrapper_tests.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/adapted/denialofservice_tests.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/adapted/descriptor_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/disconnected_transactions.cpp
  ${PROJECT_SOURCE_DIR}/src/test/feefrac_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/feerounder_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/flatfile_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/fs_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/getarg_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/hash_tests.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/adapted/headers_sync_chainwork_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/httpserver_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/i2p_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/interfaces_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/key_io_tests.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/adapted/key_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/logging_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/mempool_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/merkle_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/merkleblock_tests.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/adapted/miner_tests.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/adapted/miniminer_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/miniscript_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/minisketch_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/mock_process.cpp
  ${PROJECT_SOURCE_DIR}/src/test/multisig_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/bip328_tests.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/adapted/net_peer_connection_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/net_peer_eviction_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/net_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/netbase_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/node_init_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/node_warnings_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/orphanage_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/pcp_tests.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/adapted/peerman_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/pmt_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/policyestimator_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/pool_tests.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/adapted/pow_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/prevector_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/private_broadcast_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/raii_event_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/random_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/rbf_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/rest_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/result_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/reverselock_tests.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/adapted/rpc_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/sanity_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/scheduler_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/script_assets_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/script_p2sh_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/script_parse_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/script_segwit_tests.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/adapted/script_standard_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/script_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/scriptnum_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/serfloat_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/serialize_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/settings_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/sighash_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/sigopcount_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/skiplist_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/sock_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/span_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/streams_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/sync_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/system_ram_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/system_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/testnet4_miner_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/threadpool_tests.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/adapted/timeoffsets_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/torcontrol_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/transaction_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/translation_tests.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/adapted/txdownload_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/txgraph_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/txindex_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/txospenderindex_tests.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/adapted/txpackage_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/txreconciliation_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/txrequest_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/txvalidation_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/txvalidationcache_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/uint256_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/util_check_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/util_expected_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/util_string_tests.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/adapted/util_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/util_threadnames_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/util_trace_tests.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/adapted/validation_block_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/validation_chainstate_tests.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/adapted/validation_chainstatemanager_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/validation_flush_tests.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/adapted/validation_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/validationinterface_tests.cpp
  ${PROJECT_SOURCE_DIR}/src/test/versionbits_tests.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/pocx_wire_tests.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/pocx_real_proof_tests.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/pocx_tests.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/pocx_simd_tests.cpp
)
if(ENABLE_WALLET)
  list(APPEND POCX_TEST_SOURCES
    # The production scheduler/builder is linked only with wallet support.
    ${CMAKE_CURRENT_SOURCE_DIR}/pocx_block_builder_tests.cpp
    ${PROJECT_SOURCE_DIR}/src/wallet/test/init_test_fixture.cpp
    ${PROJECT_SOURCE_DIR}/src/wallet/test/wallet_test_fixture.cpp
    ${PROJECT_SOURCE_DIR}/src/wallet/test/db_tests.cpp
    ${PROJECT_SOURCE_DIR}/src/wallet/test/coinselector_tests.cpp
    ${PROJECT_SOURCE_DIR}/src/wallet/test/coinselection_tests.cpp
    ${PROJECT_SOURCE_DIR}/src/wallet/test/feebumper_tests.cpp
    ${PROJECT_SOURCE_DIR}/src/wallet/test/group_outputs_tests.cpp
    ${PROJECT_SOURCE_DIR}/src/wallet/test/init_tests.cpp
    ${PROJECT_SOURCE_DIR}/src/wallet/test/ismine_tests.cpp
    ${PROJECT_SOURCE_DIR}/src/wallet/test/psbt_wallet_tests.cpp
    ${PROJECT_SOURCE_DIR}/src/wallet/test/scriptpubkeyman_tests.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/adapted/spend_tests.cpp
    ${PROJECT_SOURCE_DIR}/src/wallet/test/wallet_crypto_tests.cpp
    ${PROJECT_SOURCE_DIR}/src/wallet/test/wallet_rpc_tests.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/adapted/wallet_tests.cpp
    ${PROJECT_SOURCE_DIR}/src/wallet/test/wallet_transaction_tests.cpp
    ${PROJECT_SOURCE_DIR}/src/wallet/test/walletdb_tests.cpp
    ${PROJECT_SOURCE_DIR}/src/wallet/test/walletload_tests.cpp
  )
endif()
if(ENABLE_IPC)
  list(APPEND POCX_TEST_SOURCES
    ${PROJECT_SOURCE_DIR}/src/ipc/test/ipc_tests.cpp
  )
endif()
